[project]
site_name = "POP wiki"

site_description = "Puzzles Offer Pleasure!"
site_author = "Epi"
site_url = "https://puzzle.episvr.com/"

copyright = """
Copyright &copy; 2026 Epi
All Rights Reserved
"""

docs_dir = "docs"      # 文档目录，默认：docs
site_dir = "site"      # 输出目录，默认：site

extra_css = ["stylesheets/extra.css"]
extra_javascript = ["javascripts/extra.js"]


nav = [
    { "主页" = "index.md" },
    { "快速开始" = [
        { "急速入门" = "Started/index.md" },
        { "Puzzlehunt 介绍" = "Started/detail.md"},
        { "5 分钟解释 puzzlehunt" = "Started/simple.md" },
    ] },
    {"每日活动"="Games/index.md"},
    { "克隆文档" = [
        {"一个声明"="Clone/index.md"},
        {"尝试了吗"="Clone/try.md"},
    ] },
    { "链接仓库" = [
        {"谜题日历"="Resources/00calendar.md"},
        {"百科仓库"="Resources/01wiki.md"},
        {"谜题仓库"="Resources/02repository.md"},
        {"史官记录"="Resources/03history.md"},
        {"解题工具"="Resources/04tools.md"},
        {"其他记录"="Resources/05other.md"},
        {"我的推荐"="Resources/06recommends.md"},
    ] },
    { "我的谜题" = [
        {"非马"= "Puzzles/01/puzzle.md"},
        {"小谜"= "Puzzles/02/puzzle.md"},
        {"三极"= "Puzzles/03/puzzle.md"},
    ] },
    { "题解记录"=[
        {"首页"="Blogs/"},
        {"那篇博客的谜题"="Blogs/01"},
        {"zelda-minihunt"="Blogs/02"},
    ]},
    { "友情链接"= "Friend/"},
]

# ----------------------------------------------------------------------------
# Section for configuring theme options
# ----------------------------------------------------------------------------
[project.theme]

variant = "modern"
language = "zh"
features = [
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.tracking",
    "navigation.tabs",
    "search.suggest",
]


# Zensical allows you to override specific blocks, partials, or whole
# templates as well as to define your own templates. To do this, uncomment
# the custom_dir setting below and set it to a directory in which you
# keep your template overrides.
#
# Read more:
# - https://zensical.org/docs/customization/#extending-the-theme
#
#custom_dir = "overrides"

# With the "favicon" option you can set your own image to use as the icon
# browsers will use in the browser title bar or tab bar. The path provided
# must be relative to the "docs_dir".
#
# Read more:
# - https://zensical.org/docs/setup/logo-and-icons/#favicon
# - https://developer.mozilla.org/en-US/docs/Glossary/Favicon
#
#favicon = "images/favicon.png"



# ----------------------------------------------------------------------------
# You can configure your own logo to be shown in the header using the "logo"
# option in the "theme" subsection. The logo must be a relative path to a file
# in your "docs_dir", e.g., to use `docs/assets/logo.png` you would set:
# ----------------------------------------------------------------------------
#logo = "assets/logo.png"

# ----------------------------------------------------------------------------
# If you don't have a dedicated project logo, you can use a built-in icon from
# the icon sets shipped in Zensical. Please note that the setting lives in a
# different subsection, and that the above take precedence over the icon.
#
# Read more:
# - https://zensical.org/docs/setup/logo-and-icons
# - https://github.com/zensical/ui/tree/master/dist/.icons
# ----------------------------------------------------------------------------
#[project.theme.icon]
#logo = "lucide/smile"

# ----------------------------------------------------------------------------
# In the "font" subsection you can configure the fonts used. By default, fonts
# are loaded from Google Fonts, giving you a wide range of choices from a set
# of suitably licensed fonts. There are options for a normal text font and for
# a monospaced font used in code blocks.
# ----------------------------------------------------------------------------
#[project.theme.font]
#text = "Inter"
#code = "Jetbrains Mono"

# ----------------------------------------------------------------------------
# In the "palette" subsection you can configure options for the color scheme.
# You can configure different color schemes, e.g., to turn on dark mode,
# that the user can switch between. Each color scheme can be further
# customized.
#
# Read more:
# - https://zensical.org/docs/setup/colors/
# ----------------------------------------------------------------------------

# 自动模式（跟随系统）
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle = { icon = "material/link", name = "关闭自动模式" }

# 日间模式
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "indigo"
accent = "indigo"
toggle = { icon = "material/toggle-switch", name = "切换至夜间模式" }

# 夜间模式
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "indigo"
accent = "indigo"
toggle = { icon = "material/toggle-switch-off-outline", name = "切换至日间模式" }

# ----------------------------------------------------------------------------
# The "extra" section contains miscellaneous settings.
# ----------------------------------------------------------------------------
#[[project.extra.social]]
#icon = "fontawesome/brands/github"
#link = "https://github.com/user/repo"